export const AUTH_USER_QUERY_KEY = 'AUTH_USER';
export const AUTH_UPDATE_USER_MUTATION_KEY = 'AUTH_UPDATE_USER';
export const AUTH_SIGNIN_USER_MUTATION_KEY = 'AUTH_SIGNIN_USER';
export const AUTH_SIGNUP_USER_MUTATION_KEY = 'AUTH_SIGNUP_USER';
export const AUTH_REFRESH_TOKEN_USER_MUTATION_KEY = 'AUTH_REFRESH_TOKEN_USER';
